### ISSUE TITLE
Signing body/payload

### ISSUE THREAD

**Issue by BWWIT** [jchristn/AWSSignatureGenerator#1]
Thanks for the great work with this library.

I've got it to work perfectly doing GET requests.

But I have trouble doing a PUT request (create new object) using your test-program included in the project.
The body is just a simple "Hello World" text.
But I get the error
```
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>Signature validation failed</Message>
</Error>
```
curl cmd:
```
curl --location --request PUT https://s3.eu-central-003.backblazeb2.com/WIT-TEST/MyObjKey \
--header 'content-length: 11' \
--header 'content-type: text/plain' \
--header 'host: s3.eu-central-003.backblazeb2.com:443' \
--header 'x-amz-content-sha256: a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e' \
--header 'x-amz-date: 20240203T101826Z' \
--header 'Authorization: AWS4-HMAC-SHA256 Credential=003159a457dcdb50000000044/20240203/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=958279feb33d540428bab5ffd0884e64a52912befae9be28d68b6a994f20692c' \
 --data 'Hello World'
```

I've tried to change the `V4PayloadHashEnum` value to Unsigned, but it did change anything.
![body](https://github.com/jchristn/AWSSignatureGenerator/assets/151644805/9a31558c-7a47-4dfd-9255-9c54701cd009)

I assume the payload is to be included in the calculation of the authentication signature?
If that is true, does your library support this? I looked in the code but I can't see where it is included.

**Comment by BWWIT** [comment]
I think I found my answer in your S3lite project ;-)
![DataHash](https://github.com/jchristn/AWSSignatureGenerator/assets/151644805/15fca3a9-0211-4ccb-88f6-56f396278562)

**Comment by BWWIT** [comment]
I think I found my answer in your S3Lite project :-)

![DataHash](https://github.com/jchristn/AWSSignatureGenerator/assets/151644805/794becaf-723f-41d9-b3d3-f002761d5947)

**Comment by BWWIT** [comment]
![DataHash2](https://github.com/jchristn/AWSSignatureGenerator/assets/151644805/646b7839-72c9-41af-95ad-f77fb85885a2)

**Comment by jchristn** [comment]
Hi @BWWIT I'm glad it's working for you!  Please let me know of any other issues you find!
